language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: CLZmelvF+zmvNUaAO0ohh3YJUw1hunZ/CPkVBlxCymKzSZKjwnHzVqrlulbOd+yuym61FXSpu3lWi90tSrnB2Lm9wX3uWW82YtIgr9wXJLwnCoxw0vUWclrsxNyZmjknXrrtPZ/R4vstro/NqG7d1VZ/9Sm5PKPp4zM16ucmG3TljVs5Q6di4Z/Mueurubti2ADODipeDwzuMZVOyndPpCtz92kuGrDGtw4+6HY2Y6hhmOcDUzuq7j91fd42uB3TynbwojqO3qDsT+/XqqJpTrGXpr6g9VaACcENK+vdLN9B72P4MwAcs7oimBJZH/qOD0PESvT21kK80i2Yqmh4Fq9NCWjPHPKKMoF2vqkq4AZBBw7B9BFi/G6qD5CFULZSjAKlSyptuosYIdOhvJSgmshNB67y2Pn8Y8z0XPdiwxYJerfmtuZ38ynYmHywXHkPMdlmMcNVPJ5Dw4LrEbi3WTIN/BnExfB/viBzGD31B46mB2AX09yLcIkN3vOYJ2DwCtKX5WNPum2eWoX766PlXoX4MRf76Ldp4ujyXdGq0r8fKHz2C1iJPXtCZAtw/2m8c2V5B4RoFcQN6FCJ8hp986VMTHktdpCZPpHIuqrC6SJusGKEsks2N/JCrJR+ShfV+dOaLWMBiZ34yBpjzc3melShlYGAr/V/3bSkzKwWCqo=
    - secure: P8VR8Ehiq1ybE/2JyvMeVsKWb/j4XJlUjDetnbIq1OMmP0A2pS+5mFm0LqYbzpXmkZKTiG2UCBTXYBZpQyKi9NtehRiFNJHp2crxCTrBXe2tJIwOx46f/i48XFXMI039b0eb4kQfeDJmIhl0KNavXo2pp1kZ6M96U5mv+XDGKoOeSu9WR0ihAJwmpitWVQsDh2qQbr+mTj+UOgAgZmB03PAHfsL3QYszeAC5nphF8WWx9GCDt53UHj4hDibyM1qGBfV1GMg25KD4shsevh1hIkVk8eh8mmLoUYI/8SQbjCX1E1otbNKS0IpdwOYwU7Q3VMZFWL5IMWg1o0G0ZjVy8wQAcV+Diei4o8HU/KMrev3ILDZQs/Qf9DKqybATGwomZLvD2ygiwfyG4tGBvtjPeQboEVPq/7QUGQtbG+6TlqEoMT9e0DC3lsQlh3zgpp7epp+ojkw0J8Ht1ib5+eVHlLUnfhKJlDnhznx4Namztidxahq3qwGFRyg3oUprCWIVbZjWc9VGDQLSbMLrgZ4x0334R0yOosyeV/TfeP5WbRHnZe1fv+8EUbD8Qzv9VufMIMhW5pnCRMvtEgbOO3c+Hggk9YsSg9qgDFZBNgaZZ6q2WoW8qqNGJ9iALWZgKWTSNWfoR4OsGU9+N8tg7IZozD/HmscXLbHrqYSXZkLQP2o=
    - TERM=dumb

after_success:
  - ./gradlew uploadArchives -i -s
 
install: /bin/true
after_failure: chmod +x ./travis-after-failure.sh; ./travis-after-failure.sh